name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodejs: [13]

    name: Node.js ${{ matrix.nodejs }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - run: npm install
    - run: npm test

